// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for CallState.
const (
	CallStateActive   CallState = "active"
	CallStateInactive CallState = "inactive"
)

// Valid indicates whether the value is a known member of the CallState enum.
func (e CallState) Valid() bool {
	switch e {
	case CallStateActive:
		return true
	case CallStateInactive:
		return true
	default:
		return false
	}
}

// Defines values for DeviceFeatureStatus.
const (
	DeviceFeatureStatusActive   DeviceFeatureStatus = "active"
	DeviceFeatureStatusInactive DeviceFeatureStatus = "inactive"
)

// Valid indicates whether the value is a known member of the DeviceFeatureStatus enum.
func (e DeviceFeatureStatus) Valid() bool {
	switch e {
	case DeviceFeatureStatusActive:
		return true
	case DeviceFeatureStatusInactive:
		return true
	default:
		return false
	}
}

// Defines values for DeviceFeatureType.
const (
	DeviceFeatureTypeCamera DeviceFeatureType = "camera"
	DeviceFeatureTypeMic    DeviceFeatureType = "mic"
)

// Valid indicates whether the value is a known member of the DeviceFeatureType enum.
func (e DeviceFeatureType) Valid() bool {
	switch e {
	case DeviceFeatureTypeCamera:
		return true
	case DeviceFeatureTypeMic:
		return true
	default:
		return false
	}
}

// Defines values for DeviceType.
const (
	DeviceTypeLaptop DeviceType = "laptop"
	DeviceTypeMobile DeviceType = "mobile"
	DeviceTypePC     DeviceType = "pc"
)

// Valid indicates whether the value is a known member of the DeviceType enum.
func (e DeviceType) Valid() bool {
	switch e {
	case DeviceTypeLaptop:
		return true
	case DeviceTypeMobile:
		return true
	case DeviceTypePC:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseCode.
const (
	Duplicate      ErrorResponseCode = "duplicate"
	EntityNotFound ErrorResponseCode = "entity_not_found"
	Internal       ErrorResponseCode = "internal"
	Invalid        ErrorResponseCode = "invalid"
	RouteNotFound  ErrorResponseCode = "route_not_found"
	Unauthorized   ErrorResponseCode = "unauthorized"
	Unknown        ErrorResponseCode = "unknown"
)

// Valid indicates whether the value is a known member of the ErrorResponseCode enum.
func (e ErrorResponseCode) Valid() bool {
	switch e {
	case Duplicate:
		return true
	case EntityNotFound:
		return true
	case Internal:
		return true
	case Invalid:
		return true
	case RouteNotFound:
		return true
	case Unauthorized:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseWholeRequestError.
const (
	ErrorResponseWholeRequestErrorInvalid  ErrorResponseWholeRequestError = "invalid"
	ErrorResponseWholeRequestErrorRequired ErrorResponseWholeRequestError = "required"
)

// Valid indicates whether the value is a known member of the ErrorResponseWholeRequestError enum.
func (e ErrorResponseWholeRequestError) Valid() bool {
	switch e {
	case ErrorResponseWholeRequestErrorInvalid:
		return true
	case ErrorResponseWholeRequestErrorRequired:
		return true
	default:
		return false
	}
}

// CallState Call state for the user
type CallState string

// CallStatus defines model for CallStatus.
type CallStatus = []UserStatus

// Device defines model for Device.
type Device struct {
	// Id Device ID
	Id int32 `json:"id"`

	// Name Device name
	Name string `json:"name"`

	// Type Device type
	Type DeviceType `json:"type"`
}

// DeviceFeature defines model for DeviceFeature.
type DeviceFeature struct {
	// Id Feature ID
	Id int32 `json:"id"`

	// LastActive Last active timestamp in RFC3339 format
	LastActive *time.Time `json:"lastActive,omitempty"`

	// Status Device feature status
	Status DeviceFeatureStatus `json:"status"`

	// Type Device feature type
	Type DeviceFeatureType `json:"type"`
}

// DeviceFeatureInput defines model for DeviceFeatureInput.
type DeviceFeatureInput struct {
	// Status Device feature status
	Status DeviceFeatureStatus `json:"status"`

	// Type Device feature type
	Type DeviceFeatureType `json:"type"`
}

// DeviceFeatureStatus Device feature status
type DeviceFeatureStatus string

// DeviceFeatureType Device feature type
type DeviceFeatureType string

// DeviceInput defines model for DeviceInput.
type DeviceInput struct {
	// Name Device name
	Name string `json:"name"`

	// Type Device type
	Type DeviceType `json:"type"`
}

// DeviceStatus defines model for DeviceStatus.
type DeviceStatus struct {
	Features []DeviceFeature `json:"features"`

	// Id Device ID
	Id int32 `json:"id"`

	// Name Device name
	Name string `json:"name"`

	// Type Device type
	Type DeviceType `json:"type"`
}

// DeviceType Device type
type DeviceType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Body *ErrorResponse_Body `json:"body,omitempty"`

	// Code Error code
	Code      ErrorResponseCode        `json:"code"`
	Query     *ErrorResponse_Query     `json:"query,omitempty"`
	UrlParams *ErrorResponse_UrlParams `json:"urlParams,omitempty"`
}

// ErrorResponse_Body defines model for ErrorResponse.Body.
type ErrorResponse_Body struct {
	union json.RawMessage
}

// ErrorResponseCode Error code
type ErrorResponseCode string

// ErrorResponse_Query defines model for ErrorResponse.Query.
type ErrorResponse_Query struct {
	union json.RawMessage
}

// ErrorResponse_UrlParams defines model for ErrorResponse.UrlParams.
type ErrorResponse_UrlParams struct {
	union json.RawMessage
}

// ErrorResponseRequestFieldError defines model for ErrorResponseRequestFieldError.
type ErrorResponseRequestFieldError map[string]string

// ErrorResponseWholeRequestError defines model for ErrorResponseWholeRequestError.
type ErrorResponseWholeRequestError string

// User defines model for User.
type User struct {
	// Id User ID
	Id int32 `json:"id"`

	// Name User name
	Name string `json:"name"`
}

// UserStatus defines model for UserStatus.
type UserStatus struct {
	Devices []DeviceStatus `json:"devices"`

	// State Call state for the user
	State CallState `json:"state"`
	User  User      `json:"user"`
}

// CreateDeviceJSONRequestBody defines body for CreateDevice for application/json ContentType.
type CreateDeviceJSONRequestBody = DeviceInput

// UpsertDeviceFeatureJSONRequestBody defines body for UpsertDeviceFeature for application/json ContentType.
type UpsertDeviceFeatureJSONRequestBody = DeviceFeatureInput

// AsErrorResponseWholeRequestError returns the union data inside the ErrorResponse_Body as a ErrorResponseWholeRequestError
func (t ErrorResponse_Body) AsErrorResponseWholeRequestError() (ErrorResponseWholeRequestError, error) {
	var body ErrorResponseWholeRequestError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorResponseWholeRequestError overwrites any union data inside the ErrorResponse_Body as the provided ErrorResponseWholeRequestError
func (t *ErrorResponse_Body) FromErrorResponseWholeRequestError(v ErrorResponseWholeRequestError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorResponseWholeRequestError performs a merge with any union data inside the ErrorResponse_Body, using the provided ErrorResponseWholeRequestError
func (t *ErrorResponse_Body) MergeErrorResponseWholeRequestError(v ErrorResponseWholeRequestError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorResponseRequestFieldError returns the union data inside the ErrorResponse_Body as a ErrorResponseRequestFieldError
func (t ErrorResponse_Body) AsErrorResponseRequestFieldError() (ErrorResponseRequestFieldError, error) {
	var body ErrorResponseRequestFieldError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorResponseRequestFieldError overwrites any union data inside the ErrorResponse_Body as the provided ErrorResponseRequestFieldError
func (t *ErrorResponse_Body) FromErrorResponseRequestFieldError(v ErrorResponseRequestFieldError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorResponseRequestFieldError performs a merge with any union data inside the ErrorResponse_Body, using the provided ErrorResponseRequestFieldError
func (t *ErrorResponse_Body) MergeErrorResponseRequestFieldError(v ErrorResponseRequestFieldError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ErrorResponse_Body) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ErrorResponse_Body) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsErrorResponseWholeRequestError returns the union data inside the ErrorResponse_Query as a ErrorResponseWholeRequestError
func (t ErrorResponse_Query) AsErrorResponseWholeRequestError() (ErrorResponseWholeRequestError, error) {
	var body ErrorResponseWholeRequestError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorResponseWholeRequestError overwrites any union data inside the ErrorResponse_Query as the provided ErrorResponseWholeRequestError
func (t *ErrorResponse_Query) FromErrorResponseWholeRequestError(v ErrorResponseWholeRequestError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorResponseWholeRequestError performs a merge with any union data inside the ErrorResponse_Query, using the provided ErrorResponseWholeRequestError
func (t *ErrorResponse_Query) MergeErrorResponseWholeRequestError(v ErrorResponseWholeRequestError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorResponseRequestFieldError returns the union data inside the ErrorResponse_Query as a ErrorResponseRequestFieldError
func (t ErrorResponse_Query) AsErrorResponseRequestFieldError() (ErrorResponseRequestFieldError, error) {
	var body ErrorResponseRequestFieldError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorResponseRequestFieldError overwrites any union data inside the ErrorResponse_Query as the provided ErrorResponseRequestFieldError
func (t *ErrorResponse_Query) FromErrorResponseRequestFieldError(v ErrorResponseRequestFieldError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorResponseRequestFieldError performs a merge with any union data inside the ErrorResponse_Query, using the provided ErrorResponseRequestFieldError
func (t *ErrorResponse_Query) MergeErrorResponseRequestFieldError(v ErrorResponseRequestFieldError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ErrorResponse_Query) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ErrorResponse_Query) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsErrorResponseWholeRequestError returns the union data inside the ErrorResponse_UrlParams as a ErrorResponseWholeRequestError
func (t ErrorResponse_UrlParams) AsErrorResponseWholeRequestError() (ErrorResponseWholeRequestError, error) {
	var body ErrorResponseWholeRequestError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorResponseWholeRequestError overwrites any union data inside the ErrorResponse_UrlParams as the provided ErrorResponseWholeRequestError
func (t *ErrorResponse_UrlParams) FromErrorResponseWholeRequestError(v ErrorResponseWholeRequestError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorResponseWholeRequestError performs a merge with any union data inside the ErrorResponse_UrlParams, using the provided ErrorResponseWholeRequestError
func (t *ErrorResponse_UrlParams) MergeErrorResponseWholeRequestError(v ErrorResponseWholeRequestError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsErrorResponseRequestFieldError returns the union data inside the ErrorResponse_UrlParams as a ErrorResponseRequestFieldError
func (t ErrorResponse_UrlParams) AsErrorResponseRequestFieldError() (ErrorResponseRequestFieldError, error) {
	var body ErrorResponseRequestFieldError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorResponseRequestFieldError overwrites any union data inside the ErrorResponse_UrlParams as the provided ErrorResponseRequestFieldError
func (t *ErrorResponse_UrlParams) FromErrorResponseRequestFieldError(v ErrorResponseRequestFieldError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorResponseRequestFieldError performs a merge with any union data inside the ErrorResponse_UrlParams, using the provided ErrorResponseRequestFieldError
func (t *ErrorResponse_UrlParams) MergeErrorResponseRequestFieldError(v ErrorResponseRequestFieldError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ErrorResponse_UrlParams) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ErrorResponse_UrlParams) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
